# Build stage
FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /workspace/target/IssueTracker-0.0.1-SNAPSHOT.jar app.jar
# Install curl for healthcheck
RUN apk add --no-cache curl

EXPOSE 6969

ENTRYPOINT ["java", "-jar", "app.jar"]
