server.port=${SERVER_PORT:${PORT:6969}}
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
logging.level.org.springframework.web.cors=DEBUG
jwt.secret-key=564DDFE8C843709F13421E26F9456EAA3D5B1D7E053794BCF8560DB433566531
duplicateservice.url=http://localhost:5000
